Update docs to .NET 5
exercism/csharp pull request #1558
Opened 2021-07-16 14:32 UTC by ErikSchierboom

2021-07-17 14:43 UTC, yzAlvin commented on docs/INSTALLATION.md
> +The F# track is built on top of the [.NET](https://dotnet.microsoft.com/learn/dotnet/what-is-dotnet) platform, which runs on Windows, Linux and macOS. To build .NET projects, you can use the .NET Com
Should that say "C# Track" not "F# Track?"

2021-07-20 06:28 UTC, ErikSchierboom commented on docs/INSTALLATION.md
> +- [Visual Studio Code](https://code.visualstudio.com/download) with the [Ionide-fsharp extension](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp)
```suggestion
- [Visual Studio Code](https://code.visualstudio.com/download) with the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp)
```

2021-07-23 10:27 UTC, iHiD approved these changes

2021-07-23 11:14 UTC, wolf99 requested changes

2021-07-23 11:14 UTC, wolf99 commented on docs/INSTALLATION.md
> +The F# track is built on top of the [.NET](https://dotnet.microsoft.com/learn/dotnet/what-is-dotnet) platform, which runs on Windows, Linux and macOS. To build .NET projects, you can use the .NET Com
```suggestion
The C# track is built on top of the [.NET](https://dotnet.microsoft.com/learn/dotnet/what-is-dotnet) platform, which runs on Windows, Linux and macOS. To build .NET projects, you can use the .NET Command Line Interface (CLI). This CLI is part of the .NET SDK, which you can install by following the [installation instructions](https://dotnet.microsoft.com/download/dotnet/5.0). Note: the C# track requires SDK version 5.0 or greater.
```

2021-07-23 16:38 UTC, wolf99 approved these changes

2021-08-17 07:10 UTC, merged