Show Test Report Summary in CI
exercism/csharp pull request #2222
Opened 2024-01-31 18:50 UTC by putquo

### Description
This PR aims to resolve #1949.

### Changes
* Added [test-summary/action](https://github.com/test-summary/action) to the `Test` workflow
* Added `JunitXml.TestLogger` as a dependency to all existing exercises
* Added `JunitXml.TestLogger` as a dependency to new exercises via the `add-new-exercise.ps1` script
* Updated the `test.ps1` script to use the test logger when the `CI` environment variable evaluates to `true`

### Notes
Since the tests do not specify a namespace, the logger defaults to `UnknownNamespace`. [Here](https://github.com/putquo/csharp/actions/runs/7678263985) is an example of what this looks like.

2024-02-01 08:09 UTC, ErikSchierboom requested changes
Thanks for working on this! I'd like to suggest a slightly different approach. Right now, students will have to download the `JunitXml.TestLogger` package even if they're just working locally, which doesn't really offer them anything. What I would suggest to do instead is to modify the `test.ps1` script to dynamically add the package (via `dotnet add package JunitXml.TestLogger`) when it detects that it runs in CI.

2024-02-01 08:09 UTC, ErikSchierboom commented on .github/workflows/test.yml
> +      - uses: test-summary/action@v2
Could you pin this to a SHA? See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas

2024-02-01 16:37 UTC, putquo commented
> Thanks for working on this! I'd like to suggest a slightly different approach. Right now, students will have to download the `JunitXml.TestLogger` package even if they're just working locally, which doesn't really offer them anything. What I would suggest to do instead is to modify the `test.ps1` script to dynamically add the package (via `dotnet add package JunitXml.TestLogger`) when it detects that it runs in CI.

Good point! I have made the change as you suggested. This does increase the run time of the workflow quite a bit (if that is of any concern), but I managed to shave off about a couple of minutes with the `--no-restore` option since it will run during `dotnet test` anyway. Maybe you have some ideas if you think it may be problematic?

2024-02-02 07:03 UTC, ErikSchierboom commented
> Maybe you have some ideas if you think it may be problematic?

I think this is fine!

2024-02-02 07:03 UTC, ErikSchierboom approved these changes
Excellent work!

2024-02-02 07:04 UTC, ErikSchierboom commented
Maybe a silly question, but where can I see the summary?

2024-02-02 07:19 UTC, putquo commented
> Maybe a silly question, but where can I see the summary?

I wondered that at first too :) but you can view it over [here](https://github.com/exercism/csharp/actions/runs/7744453074). In general, you’ll need to go to the “summary” section of a workflow run (top left corner on web) and scroll to the bottom of the page to see it. It seems like you also have to be signed in to see it.

2024-02-02 07:34 UTC, ErikSchierboom commented
Right! It's unimpressive right now because everything is passing, but reading up on the docs, it will be very useful when tests are failing:

> show: the test results to summarize in a table (optional) This controls whether a test summary table is created or not, as well as what tests are included. It could be all, none, pass, skip, or fail. The default is fail - that is, the summary table will only show the failed tests. For example, if you wanted to show failed and skipped tests:

Right now finding failing tests involves some annoying text searching.

2024-02-02 07:34 UTC, merged

2024-02-02 07:34 UTC, ErikSchierboom commented
Thanks a lot! If you care for it, you'd be welcome to do the same thing for `exercism/vbnet` or `exercism/fsharp`.